config/routes.rb
Rails.application.routes.draw do
  resources :models
  devise_for :users
  # get 'profile/user/:id(.:format)' => 'profile#user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/login'  => 'profile#login', as: :login
  # get '/signup' => 'profile#signup', as: :signup
  # get '/profile/user' => 'profile#user'
  resources :profiles
  resources :guilds
  root 'profiles#index'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :guild
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  # before_action :get_token, only: [:show]

  @token = ""

  def login
  end

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    today = Date.today
    @week = today.at_beginning_of_week

    values = {
      'NameCode' => 'DITHANIAL_BYWT',
      'functionName' => 'get_hero_profile',
      # 'serverToken' => @@token,
      'clientVersion' => '4.3.0'
   }

    headers = {
        content_type: 'application/json'
    }

    @response = RestClient.post 'https://pcmob.parse.gemsofwar.com/call_function', values, headers

    @response = JSON.parse(@response)
    @troop_count = 0
    @response["result"].each do |data, result|
      if data == "ProfileData"
        result.each do |key, value|
          if key == "Name"
            @username = value
            next
          end
          if key == "Level"
            @level = value
            next
          end
          if key == "NameCode"
            @invite_code = value
            next
          end
          if key == "GuildGoldContributedWeekly"
            @gold = value
            next
          end
          if key == "GuildSealsWeekly"
            @seals = value
            next
          end
          if key == "GuildTrophiesWeekly"
            @trophies = value
            next
          end
          if key == "GuildName"
            @guild = value
            next
          end
          if key == "NumKingdomsOwned"
            @kingdoms = value
            next
          end
          if key == "Troops"
            value.each do |count|
              @troop_count += 1
            end
            next
          end
        end
      end
      puts @troop_count
      # Profile.create(player_name: @username,
      #                player_level: @level,
      #                kingdom_status: @kingdoms,
      #                troop_count: @troop_count,
      #                gold_donated: @gold,
      #                seals_donated: @seals,
      #                trophies_earned: @trophies,
      #                invite_code: @invite_code,
      #                user_id: @profile.id,
      #                guild_id: 1)
    end

    # @username = @username.parse_JSON("result")
    # puts @username
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.fetch(:profile, {})
    end


end

# curl --header "Content-Type: application/json" \
#   --request POST \
#   --data "{
#         'clientVersion': '4.3.0',
#         'functionName': 'login_user',
#         'username': '4RNhuB1EYEBk',
#         'password': 'ed3xcfXuYQYZ'
#       }" \
#   https://pcmob.parse.gemsofwar.com/call_function

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
=begin

  values = '{
      "NameCode": "DITHANIAL_BYWT",
      "functionName": "get_hero_profile",
      "serverToken": "Server Token",
      "clientVersion": "4.3.007"
  }'

  headers = {
      content_type: 'application/json'
  }

  @response = RestClient.post 'http://pcmob/parse.gemsofwar.com/call_function', values, headers
=end

end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/login.html.erb
<div class="col-lg-4 offset-lg-4 profile-font login-form">
  <form>
    <div class="form-group">
      <label>Invite Code</label>
      <input type="text" class="form-control" placeholder="Enter code">
<!--      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
    </div>
    <div class="form-group">
      <label>Password</label>
      <input type="password" class="form-control" placeholder="Password">
    </div>
<!--    <div class="form-group form-check">-->
<!--      <input type="checkbox" class="form-check-input">-->
<!--      <label class="form-check-label">Check me out</label>-->
<!--    </div>-->
    <button type="submit" class="btn btn-primary">Log In</button>
  </form>
</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="profile">
  <div class="row">
    <div class="col-xs-4">
      <%= image_tag 'dith.png', class: 'profile-image' %>
    </div>
    <div class="col-xs-8 user-info profile-font">
      <h1><%= @username %></h1>
      <h1>Level: <%= @level %></h1>
      <h1><%= link_to "Guild: #{@guild}", guilds_path %></h1>
      <div align="center" id="stats">
        <h3>STATS FOR THE WEEK OF <%= @week %></h3>
        <h3>Trophies earned: <%= @trophies %></h3>
        <h3>Seals earned: <%= @seals %></h3>
        <h3>Gold donated: <%= @gold %></h3>
      </div>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>

<!--<%#= link_to 'Edit', edit_profile_path(@profile) %> |-->
<%#= link_to 'Back', profiles_path %>
<div class="profile-font">
  <%#= @username %>
  <%#= @response %>
</div>