config/routes.rb
Rails.application.routes.draw do
  resources :models
  devise_for :users
  # get 'profile/user/:id(.:format)' => 'profile#user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/login'  => 'profile#login', as: :login
  # get '/signup' => 'profile#signup', as: :signup
  # get '/profile/user' => 'profile#user'
  resources :profiles
  resources :guilds
  root 'profiles#index'

end

app/models/guild.rb
class Guild < ApplicationRecord
  has_many :profiles
end

app/controllers/guilds_controller.rb
class GuildsController < ApplicationController
  before_action :set_guild, only: [:show, :edit, :update, :destroy]
  # before_action :get_token, only: [:show]

  # GET /guilds
  # GET /guilds.json
  def index
    @guilds = Guild.all
  end

  # GET /guilds/1
  # GET /guilds/1.json
  def show
    @show_token = get_token
    @epoch = (Time.now.to_f * 1000).floor

    values = {
      'functionName' => 'get_guild_data',
      'username' => '4RNhuB1EYEBk',
      'password' => 'ed3xcfXuYQYZ',
      'clientCalltime' => @epoch,
      'clientVersion' => '4.3.0.007',
      'serverToken' => @show_token
    }

    headers = {
        content_type: 'application/json'
    }
    puts @show_token
    puts @epoch
    @response = RestClient.post 'https://pcmob.parse.gemsofwar.com/call_function', values, headers
  end

  # GET /guilds/new
  def new
    @guild = Guild.new
  end

  # GET /guilds/1/edit
  def edit
  end

  # POST /guilds
  # POST /guilds.json
  def create
    @guild = Guild.new(guild_params)

    respond_to do |format|
      if @guild.save
        format.html { redirect_to @guild, notice: 'Guild was successfully created.' }
        format.json { render :show, status: :created, location: @guild }
      else
        format.html { render :new }
        format.json { render json: @guild.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guilds/1
  # PATCH/PUT /guilds/1.json
  def update
    respond_to do |format|
      if @guild.update(guild_params)
        format.html { redirect_to @guild, notice: 'Guild was successfully updated.' }
        format.json { render :show, status: :ok, location: @guild }
      else
        format.html { render :edit }
        format.json { render json: @guild.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guilds/1
  # DELETE /guilds/1.json
  def destroy
    @guild.destroy
    respond_to do |format|
      format.html { redirect_to guilds_url, notice: 'Guild was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guild
      @guild = Guild.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guild_params
      params.fetch(:guild, {})
    end
  def get_token
    values = {
        "clientVersion" => '4.3.0',
        "functionName" => 'login_user',
        "username" => '4RNhuB1EYEBk',
        "password" => 'ed3xcfXuYQYZ'
    }

    @token_result = RestClient.post 'https://pcmob.parse.gemsofwar.com/call_function', values, content_type: "application/json"

    @token_result = JSON.parse(@token_result)
    # puts @token_result
    @token_result["result"].each do |key, value|
      if key == "ServerToken"
        @token = value
      end
    end
    # puts @token
    return @token
  end
end

app/helpers/guilds_helper.rb
module GuildsHelper
end

app/views/guilds/_form.html.erb
<%= form_with(model: guild, local: true) do |form| %>
  <% if guild.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guild.errors.count, "error") %> prohibited this guild from being saved:</h2>

      <ul>
      <% guild.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guilds/edit.html.erb
<h1>Editing Guild</h1>

<%= render 'form', guild: @guild %>

<%= link_to 'Show', @guild %> |
<%= link_to 'Back', guilds_path %>

app/views/guilds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guilds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guilds.each do |guild| %>
      <tr>
        <td><%= link_to 'Show', guild %></td>
        <td><%= link_to 'Edit', edit_guild_path(guild) %></td>
        <td><%= link_to 'Destroy', guild, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guild', new_guild_path %>

app/views/guilds/new.html.erb
<h1>New Guild</h1>

<%= render 'form', guild: @guild %>

<%= link_to 'Back', guilds_path %>

app/views/guilds/show.html.erb
<p id="notice"><%= notice %></p>
<%= @token %><br/>
<%= @response %>

<h1></h1>